version: '3'
services:

    db:
        image: postgres
        container_name: gostack_desafio06_postgres
        restart: always
        tty: true
        ports:
          - "5432:5432"
        volumes:
          - ./pg-init-scripts:/docker-entrypoint-initdb.d
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=docker
          - POSTGRES_MULTIPLE_DATABASES=gostack_desafio06,gostack_desafio06_tests
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
